"""
psiqit/utils/random.py
============================================================
Random Quantum State and Operator Generation
============================================================

Tools for generating random quantum objects:
    • Random pure states (Haar measure)
    • Random density matrices
    • Random unitary operators
    • Random Hermitian operators
    • Random Pauli rotations

Random generation is essential for testing quantum algorithms, simulating
random circuits, and benchmarking quantum protocols. This module provides
functions to generate random quantum states and operators with various
probability distributions (Haar measure for unitaries and pure states).

Example:
    >>> from psiqit.utils.random import random_state, random_unitary, random_density_matrix
    >>> from psiqit.utils.validation import is_unitary, is_hermitian
    >>> 
    >>> # Random pure state
    >>> psi = random_state(2)
    >>> print(psi.is_normalized)
    True
    >>> 
    >>> # Random unitary matrix
    >>> U = random_unitary(2)
    >>> print(is_unitary(U).is_valid)
    True
    >>> 
    >>> # Random density matrix
    >>> rho = random_density_matrix(2)
    >>> from psiqit.utils.validation import is_density_matrix
    >>> print(is_density_matrix(rho).is_valid)
    True

References:
    F. Mezzadri, "How to generate random matrices from the classical compact groups,"
    Notices of the AMS, 54(5):592-604, 2007.
    I. Bengtsson and K. Życzkowski, "Geometry of Quantum States,"
    Cambridge University Press, 2006.
"""

import math
import random
from typing import List, Union, Optional, Tuple
from dataclasses import dataclass

from ..math.qalgebra import mul, dagger, trace, eye, conj, transpose, kron
from ..quantum.state import Ket
from ..quantum.operator import Operator


@dataclass
class RandomResult:
    """
    Result container for random generation.

    Attributes:
        result: The generated random object.
        seed: Random seed used (if any).
        type: Type of object generated ('state', 'density_matrix', 'unitary', etc.).
        dimension: Dimension of the generated object.

    Examples:
        >>> result = RandomResult(result=psi, seed=42, type='state', dimension=2)
        >>> print(result)
        Random state (dim=2, seed=42)
    """
    result: any
    seed: Optional[int]
    type: str
    dimension: int
    
    def __str__(self) -> str:
        """
        Return a human-readable string representation.

        Returns:
            String showing type, dimension, and seed.
        """
        return f"Random {self.type} (dim={self.dimension}, seed={self.seed})"


# ============================================================
# Random State Generation
# ============================================================

def random_state(dim: int, seed: Optional[int] = None) -> Ket:
    """
    Generate a random pure state according to the Haar measure.

    The state is generated by taking random complex Gaussian entries
    and normalizing. This produces a uniformly random state on the
    sphere in C^d.

    Args:
        dim: Dimension of Hilbert space.
        seed: Random seed for reproducibility.

    Returns:
        Random normalized pure state.

    Examples:
        >>> psi = random_state(2)
        >>> print(psi.is_normalized)
        True
        >>> 
        >>> # Reproducible random state
        >>> psi1 = random_state(2, seed=42)
        >>> psi2 = random_state(2, seed=42)
        >>> assert psi1.data == psi2.data
        >>> 
        >>> # 4-dimensional (2-qubit) random state
        >>> psi = random_state(4)
        >>> print(psi.dim)
        4
    """
    if seed is not None:
        random.seed(seed)
    
    # Generate random complex amplitudes
    amplitudes = []
    for _ in range(dim):
        real = random.gauss(0, 1)
        imag = random.gauss(0, 1)
        amplitudes.append(complex(real, imag))
    
    # Normalize
    norm = math.sqrt(sum(abs(a)**2 for a in amplitudes))
    if norm > 0:
        amplitudes = [a / norm for a in amplitudes]
    
    return Ket(amplitudes, _normalized=True)


def random_qubit_state(seed: Optional[int] = None) -> Ket:
    """
    Generate a random single-qubit state.

    Args:
        seed: Random seed for reproducibility.

    Returns:
        Random normalized qubit state.

    Examples:
        >>> psi = random_qubit_state()
        >>> print(psi.dim)
        2
        >>> 
        >>> # With seed for reproducibility
        >>> psi = random_qubit_state(seed=42)
    """
    return random_state(2, seed)


def random_n_qubit_state(n_qubits: int, seed: Optional[int] = None) -> Ket:
    """
    Generate a random n-qubit state.

    Args:
        n_qubits: Number of qubits.
        seed: Random seed for reproducibility.

    Returns:
        Random normalized n-qubit state.

    Examples:
        >>> psi = random_n_qubit_state(3)  # 3-qubit random state
        >>> print(psi.dim)  # 2^3 = 8
        8
    """
    dim = 2 ** n_qubits
    return random_state(dim, seed)


# ============================================================
# Random Density Matrix Generation
# ============================================================

def random_density_matrix(dim: int, rank: Optional[int] = None, 
                          seed: Optional[int] = None) -> List[List[complex]]:
    """
    Generate a random density matrix.

    The density matrix is generated as ρ = AA† / Tr(AA†), where A is a
    dim × rank matrix with random complex Gaussian entries. This produces
    a random positive semidefinite matrix with the specified rank.

    Args:
        dim: Dimension of Hilbert space.
        rank: Rank of density matrix (if None, full rank = dim).
        seed: Random seed for reproducibility.

    Returns:
        Random density matrix (positive semidefinite, trace = 1).

    Raises:
        ValueError: If rank > dim.

    Examples:
        >>> # Full rank density matrix (maximally mixed on average)
        >>> rho = random_density_matrix(2)
        >>> 
        >>> # Rank-1 density matrix (pure state)
        >>> rho = random_density_matrix(2, rank=1)
        >>> from psiqit.utils.conversion import is_pure_state
        >>> print(is_pure_state(rho))
        True
        >>> 
        >>> # 3x3 density matrix with rank 2
        >>> rho = random_density_matrix(3, rank=2)
    """
    if seed is not None:
        random.seed(seed)
    
    if rank is None:
        rank = dim
    elif rank > dim:
        raise ValueError(f"Rank {rank} cannot exceed dimension {dim}")
    
    # Generate random matrix A (dim × rank)
    A = []
    for _ in range(dim):
        row = []
        for _ in range(rank):
            real = random.gauss(0, 1)
            imag = random.gauss(0, 1)
            row.append(complex(real, imag))
        A.append(row)
    
    # Make positive semidefinite: ρ = A A†
    rho = [[0j] * dim for _ in range(dim)]
    for i in range(dim):
        for j in range(dim):
            for k in range(rank):
                rho[i][j] += A[i][k] * A[j][k].conjugate()
    
    # Normalize to trace 1
    tr = trace(rho)
    tr_real = tr.real if hasattr(tr, 'real') else tr
    
    if tr_real > 0:
        for i in range(dim):
            for j in range(dim):
                rho[i][j] /= tr_real
    
    return rho


def random_qubit_density_matrix(seed: Optional[int] = None) -> List[List[complex]]:
    """
    Generate a random single-qubit density matrix.

    Args:
        seed: Random seed for reproducibility.

    Returns:
        Random 2x2 density matrix.

    Examples:
        >>> rho = random_qubit_density_matrix()
        >>> from psiqit.utils.validation import is_density_matrix
        >>> print(is_density_matrix(rho).is_valid)
        True
    """
    return random_density_matrix(2, seed=seed)


def _eigen(matrix):
    """
    Compute eigenvalues and eigenvectors (simplified for small matrices).

    This is a fallback when numpy is not available.
    """
    # For small matrices, use numpy if available
    try:
        import numpy as np
        M = np.array(matrix, dtype=complex)
        vals, vecs = np.linalg.eig(M)
        return vals.tolist(), vecs.T.tolist()
    except ImportError:
        # Fallback for 2x2 matrices
        if len(matrix) == 2:
            a, b = matrix[0][0], matrix[0][1]
            c, d = matrix[1][0], matrix[1][1]
            
            trace_val = a + d
            det_val = a * d - b * c
            
            disc = trace_val**2 - 4 * det_val
            sqrt_disc = math.sqrt(disc) if disc.real >= 0 else math.sqrt(disc)
            
            val1 = (trace_val + sqrt_disc) / 2
            val2 = (trace_val - sqrt_disc) / 2
            
            # Simple eigenvectors
            if abs(b) > 1e-10:
                vec1 = [b, val1 - a]
                vec2 = [b, val2 - a]
            else:
                vec1 = [1, 0]
                vec2 = [0, 1]
            
            # Normalize
            norm1 = math.sqrt(abs(vec1[0])**2 + abs(vec1[1])**2)
            norm2 = math.sqrt(abs(vec2[0])**2 + abs(vec2[1])**2)
            vec1 = [v / norm1 for v in vec1]
            vec2 = [v / norm2 for v in vec2]
            
            return [val1, val2], [vec1, vec2]
        else:
            raise NotImplementedError("Eigen decomposition for larger matrices requires numpy")


# ============================================================
# Random Operator Generation
# ============================================================

def random_unitary(dim: int, seed: Optional[int] = None) -> List[List[complex]]:
    """
    Generate a random unitary matrix according to the Haar measure.

    The algorithm generates a random complex matrix with Gaussian entries,
    performs QR decomposition, and adjusts the diagonal of R to be positive.

    Args:
        dim: Dimension of the unitary matrix.
        seed: Random seed for reproducibility.

    Returns:
        Random unitary matrix.

    Examples:
        >>> U = random_unitary(2)
        >>> from psiqit.utils.validation import is_unitary
        >>> print(is_unitary(U).is_valid)
        True
        >>> 
        >>> # 4x4 unitary (2-qubit gate)
        >>> U = random_unitary(4)
    """
    if seed is not None:
        random.seed(seed)
    
    # Generate random complex matrix
    Z = []
    for _ in range(dim):
        row = []
        for _ in range(dim):
            real = random.gauss(0, 1)
            imag = random.gauss(0, 1)
            row.append(complex(real, imag))
        Z.append(row)
    
    # QR decomposition
    Q, R = _qr_decomposition(Z)
    
    # Make diagonal of R positive
    for i in range(dim):
        if R[i][i].real < 0:
            for j in range(dim):
                Q[j][i] *= -1
    
    return Q


def random_hermitian(dim: int, seed: Optional[int] = None) -> List[List[complex]]:
    """
    Generate a random Hermitian matrix.

    The matrix is generated as H = (A + A†)/2, where A is a random
    complex matrix with Gaussian entries.

    Args:
        dim: Dimension of the Hermitian matrix.
        seed: Random seed for reproducibility.

    Returns:
        Random Hermitian matrix.

    Examples:
        >>> H = random_hermitian(2)
        >>> from psiqit.utils.validation import is_hermitian
        >>> print(is_hermitian(H).is_valid)
        True
        >>> 
        >>> # Random Hamiltonian for a 3-level system
        >>> H = random_hermitian(3)
    """
    if seed is not None:
        random.seed(seed)
    
    # Generate random matrix
    A = []
    for _ in range(dim):
        row = []
        for _ in range(dim):
            real = random.gauss(0, 1)
            imag = random.gauss(0, 1)
            row.append(complex(real, imag))
        A.append(row)
    
    # Make Hermitian: H = (A + A†)/2
    A_dag = dagger(A)
    H = [[(A[i][j] + A_dag[i][j]) / 2 for j in range(dim)] for i in range(dim)]
    
    return H


def random_positive_operator(dim: int, seed: Optional[int] = None) -> List[List[complex]]:
    """
    Generate a random positive semidefinite operator.

    The operator is generated as P = H², where H is a random Hermitian matrix.
    This guarantees that P is positive semidefinite.

    Args:
        dim: Dimension of the operator.
        seed: Random seed for reproducibility.

    Returns:
        Random positive semidefinite matrix.

    Examples:
        >>> P = random_positive_operator(2)
        >>> from psiqit.utils.validation import is_positive_semidefinite
        >>> print(is_positive_semidefinite(P).is_valid)
        True
    """
    if seed is not None:
        random.seed(seed)
    
    # Generate random Hermitian
    H = random_hermitian(dim, seed)
    
    # Square to make positive
    P = mul(H, H)
    
    return P


def random_pauli_rotation(seed: Optional[int] = None) -> Tuple[str, float]:
    """
    Generate a random Pauli rotation.

    Returns:
        Tuple of (pauli_gate, angle) where pauli_gate is 'X', 'Y', or 'Z'.

    Examples:
        >>> gate, angle = random_pauli_rotation()
        >>> print(f"Apply R{gate}({angle:.3f})")
        Apply RX(2.718)
        >>> 
        >>> # For reproducibility
        >>> gate, angle = random_pauli_rotation(seed=42)
    """
    if seed is not None:
        random.seed(seed)
    
    gates = ['X', 'Y', 'Z']
    gate = random.choice(gates)
    angle = random.uniform(0, 2 * math.pi)
    
    return gate, angle


def random_pauli_string(n_qubits: int, seed: Optional[int] = None) -> str:
    """
    Generate a random Pauli string (tensor product of Pauli operators).

    Args:
        n_qubits: Number of qubits.
        seed: Random seed for reproducibility.

    Returns:
        String like 'XIZY' where each character is I, X, Y, or Z.

    Examples:
        >>> pauli_string = random_pauli_string(3)
        >>> print(pauli_string)  # e.g., 'XIZ'
        XIZ
        >>> 
        >>> # For reproducibility
        >>> ps = random_pauli_string(4, seed=42)
    """
    if seed is not None:
        random.seed(seed)
    
    gates = ['I', 'X', 'Y', 'Z']
    return ''.join(random.choice(gates) for _ in range(n_qubits))


# ============================================================
# Helper Functions
# ============================================================

def _qr_decomposition(A):
    """
    QR decomposition using Gram-Schmidt process.

    Args:
        A: Input matrix.

    Returns:
        Tuple (Q, R) where Q is unitary and R is upper triangular.
    """
    n = len(A)
    Q = []
    
    # Transpose for column vectors
    A_cols = [[A[i][j] for i in range(n)] for j in range(n)]
    
    for j in range(n):
        v = A_cols[j][:]
        for k in range(j):
            # Projection
            dot = sum(Q[k][i].conjugate() * v[i] for i in range(n))
            for i in range(n):
                v[i] -= dot * Q[k][i]
        
        # Normalize
        norm_v = math.sqrt(sum(abs(x)**2 for x in v))
        if norm_v > 1e-12:
            v = [x / norm_v for x in v]
        else:
            v = [0.0] * n
        
        Q.append(v)
    
    # Transpose Q to get matrix
    Q_mat = [[Q[j][i] for j in range(n)] for i in range(n)]
    
    # Compute R = Q† A
    R = [[0j] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                R[i][j] += Q[i][k].conjugate() * A[k][j]
    
    return Q_mat, R


def set_random_seed(seed: int):
    """
    Set the global random seed for reproducibility.

    Args:
        seed: Random seed.

    Examples:
        >>> set_random_seed(42)
        >>> psi1 = random_state(2)
        >>> set_random_seed(42)
        >>> psi2 = random_state(2)
        >>> assert psi1.data == psi2.data
    """
    random.seed(seed)


# ============================================================
# Exports
# ============================================================

__all__ = [
    'RandomResult',
    'random_state',
    'random_qubit_state',
    'random_n_qubit_state',
    'random_density_matrix',
    'random_qubit_density_matrix',
    'random_unitary',
    'random_hermitian',
    'random_positive_operator',
    'random_pauli_rotation',
    'random_pauli_string',
    'set_random_seed',
]