"""
psiqit/qml/quantum_kernel.py
============================================================
Quantum Kernel Methods
============================================================

Quantum kernels for machine learning:
    • Quantum kernel estimation
    • Kernel alignment
    • Quantum feature maps

Quantum kernels provide a way to leverage quantum feature maps for machine
learning tasks. The kernel is defined as the squared overlap between quantum
states after applying a feature map:

    k(x, x') = |⟨φ(x)|φ(x')⟩|²

where |φ(x)⟩ is a quantum state generated by a parameterized circuit that
encodes classical data x. These kernels can be used in kernel methods like
SVM, kernel ridge regression, and kernel PCA.

Example:
    >>> from psiqit.qml.quantum_kernel import QuantumKernel
    >>> 
    >>> # Create a quantum kernel
    >>> kernel = QuantumKernel(n_qubits=2, feature_map='zz')
    >>> 
    >>> # Compute kernel between two data points
    >>> x1 = [0.2, 0.5]
    >>> x2 = [0.7, 0.3]
    >>> k = kernel.evaluate(x1, x2)
    >>> print(f"k(x1, x2) = {k:.4f}")
    >>> 
    >>> # Compute kernel matrix for a dataset
    >>> X = [[0, 0], [1, 1], [0, 1], [1, 0]]
    >>> K = kernel.kernel_matrix(X)
    >>> print(f"Kernel matrix shape: {len(K)} x {len(K[0])}")

References:
    V. Havlíček et al., "Supervised learning with quantum-enhanced feature spaces,"
    Nature, 567(7747):209-212, 2019.
    M. Schuld and F. Petruccione, "Machine learning with quantum computers,"
    Springer, 2021.
"""

import math
from typing import List, Union, Optional, Callable, Tuple
from dataclasses import dataclass

from ..circuits.circuit import QuantumCircuit
from ..quantum.state import Ket, basis
from ..quantum.operator import hadamard, pauli_x, pauli_y, pauli_z, cnot, rx, ry, rz
from ..quantum.measurement import expectation, measure
from ..utils.random import random_state


@dataclass
class KernelResult:
    """
    Result container for kernel computation.

    Attributes:
        value: The kernel value k(x, x') = |⟨φ(x)|φ(x')⟩|².
        fidelity: Fidelity between the two quantum states.
        distance: Distance metric (1 - fidelity) or other measure.

    Examples:
        >>> result = KernelResult(value=0.85, fidelity=0.85, distance=0.15)
        >>> print(f"Kernel value: {result.value:.4f}")
    """
    value: float
    fidelity: float
    distance: float


class QuantumKernel:
    """
    Quantum kernel for machine learning.

    A quantum kernel computes the similarity between two data points by
    mapping them to quantum states using a feature map and computing
    the squared overlap.

    The kernel is defined as: k(x, x') = |⟨φ(x)|φ(x')⟩|²

    Supported feature maps:
        - 'zz': Z-Z feature map with RZ gates and CZ entangling
        - 'xx': X-X feature map with RX gates and CNOT entangling

    Examples:
        >>> # Create a kernel with ZZ feature map
        >>> kernel = QuantumKernel(n_qubits=4, feature_map='zz', n_layers=2)
        >>> 
        >>> # Evaluate kernel
        >>> k = kernel.evaluate([0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8])
        >>> 
        >>> # Compute kernel matrix
        >>> X = [[0, 0], [0, 1], [1, 0], [1, 1]]
        >>> K = kernel.kernel_matrix(X)
    """
    
    def __init__(self, n_qubits: int, feature_map: str = 'zz', n_layers: int = 2):
        """
        Initialize the quantum kernel.

        Args:
            n_qubits: Number of qubits for the quantum feature map.
            feature_map: Type of feature map ('zz' or 'xx').
            n_layers: Number of layers in the feature map (default: 2).

        Examples:
            >>> kernel = QuantumKernel(n_qubits=2, feature_map='zz', n_layers=3)
        """
        self.n_qubits = n_qubits
        self.n_layers = n_layers
        self.feature_map_type = feature_map
        
        self._feature_map = self._build_feature_map()
    
    def _build_feature_map(self) -> Callable:
        """
        Build the quantum feature map circuit.

        Returns:
            A function that adds the feature map gates to a circuit.
        """
        
        def zz_feature_map(circuit: QuantumCircuit, x: List[float]):
            """
            ZZ feature map: exp(i * x_i * Z_i) * exp(i * x_i x_j * Z_i Z_j).

            This feature map creates entanglement based on products of
            features, which can capture correlations between dimensions.

            Args:
                circuit: Quantum circuit to add gates to.
                x: Feature vector.
            """
            # Single qubit rotations
            for i, xi in enumerate(x):
                if i < self.n_qubits:
                    circuit.rz(i, xi)
            
            # Entangling layers
            for _ in range(self.n_layers):
                for i in range(self.n_qubits - 1):
                    circuit.cz(i, i + 1)  # Use CZ instead of CNOT
                for i, xi in enumerate(x):
                    if i < self.n_qubits:
                        circuit.rz(i, xi)
        
        def xx_feature_map(circuit: QuantumCircuit, x: List[float]):
            """
            XX feature map using RX gates.

            This feature map uses RX rotations and CNOT entangling gates.

            Args:
                circuit: Quantum circuit to add gates to.
                x: Feature vector.
            """
            for i, xi in enumerate(x):
                if i < self.n_qubits:
                    circuit.rx(i, xi)
            
            for _ in range(self.n_layers):
                for i in range(self.n_qubits - 1):
                    circuit.cx(i, i + 1)  # Use cx (lowercase)
                for i, xi in enumerate(x):
                    if i < self.n_qubits:
                        circuit.rx(i, xi)
        
        if self.feature_map_type == 'zz':
            return zz_feature_map
        elif self.feature_map_type == 'xx':
            return xx_feature_map
        else:
            raise ValueError(f"Unknown feature map: {self.feature_map_type}")
    
    def _encode_data(self, x: List[float]) -> QuantumCircuit:
        """
        Encode classical data into a quantum state.

        The encoding starts with all qubits in |+⟩ state (superposition),
        then applies the feature map.

        Args:
            x: Feature vector.

        Returns:
            Quantum circuit that prepares |φ(x)⟩.
        """
        circuit = QuantumCircuit(self.n_qubits)
        
        # Initialize in superposition
        for i in range(self.n_qubits):
            circuit.h(i)
        
        # Apply feature map
        self._feature_map(circuit, x)
        
        return circuit
    
    def evaluate(self, x1: List[float], x2: List[float], shots: int = 1024) -> float:
        """
        Evaluate the kernel between two data points.

        The kernel value is computed as: k(x1, x2) = |⟨φ(x1)|φ(x2)⟩|²

        Args:
            x1: First data point (feature vector).
            x2: Second data point (feature vector).
            shots: Number of shots for measurement (not used in current
                  implementation, uses exact state vector simulation).

        Returns:
            Kernel value between 0 and 1.

        Examples:
            >>> kernel = QuantumKernel(n_qubits=2)
            >>> k = kernel.evaluate([0, 0], [1, 1])
            >>> print(f"Kernel: {k:.4f}")
        """
        # Create circuits for both data points
        circuit1 = self._encode_data(x1)
        circuit2 = self._encode_data(x2)
        
        # Get states
        state1 = circuit1.run()
        state2 = circuit2.run()
        
        # Compute fidelity (squared overlap)
        fidelity = abs(state1.inner(state2)) ** 2
        
        return fidelity
    
    def kernel_matrix(self, X: List[List[float]], shots: int = 1024) -> List[List[float]]:
        """
        Compute the full kernel matrix for a dataset.

        Args:
            X: List of data points (feature vectors).
            shots: Number of shots for measurement.

        Returns:
            Kernel matrix K where K[i][j] = k(X[i], X[j]).

        Examples:
            >>> X = [[0, 0], [0, 1], [1, 0], [1, 1]]
            >>> kernel = QuantumKernel(n_qubits=2)
            >>> K = kernel.kernel_matrix(X)
            >>> print(K[0][0])  # Should be 1.0
            1.0
        """
        n = len(X)
        K = [[0.0] * n for _ in range(n)]
        
        for i in range(n):
            for j in range(i, n):
                k = self.evaluate(X[i], X[j], shots)
                K[i][j] = k
                K[j][i] = k
        
        return K
    
    def kernel_alignment(self, X: List[List[float]], y: List[int], shots: int = 1024) -> float:
        """
        Compute the kernel alignment with target labels.

        Kernel alignment measures how well the kernel matrix matches
        the target kernel (1 if labels match, 0 otherwise).

        Args:
            X: List of data points.
            y: Target labels (0 or 1).
            shots: Number of shots for measurement.

        Returns:
            Kernel alignment value between 0 and 1. Higher values indicate
            better suitability for classification.

        Examples:
            >>> X = [[0, 0], [1, 1], [0, 1], [1, 0]]
            >>> y = [0, 0, 1, 1]  # XOR pattern
            >>> kernel = QuantumKernel(n_qubits=2)
            >>> alignment = kernel.kernel_alignment(X, y)
            >>> print(f"Kernel alignment: {alignment:.4f}")
        """
        K = self.kernel_matrix(X, shots)
        
        # Target kernel: K_target[i][j] = 1 if y[i] == y[j] else 0
        n = len(y)
        K_target = [[0.0] * n for _ in range(n)]
        for i in range(n):
            for j in range(n):
                K_target[i][j] = 1.0 if y[i] == y[j] else 0.0
        
        # Alignment = ⟨K, K_target⟩ / sqrt(⟨K, K⟩ * ⟨K_target, K_target⟩)
        inner_KK = sum(K[i][j] * K[i][j] for i in range(n) for j in range(n))
        inner_KtKt = sum(K_target[i][j] * K_target[i][j] for i in range(n) for j in range(n))
        inner_KKt = sum(K[i][j] * K_target[i][j] for i in range(n) for j in range(n))
        
        if inner_KK * inner_KtKt > 0:
            return inner_KKt / math.sqrt(inner_KK * inner_KtKt)
        return 0.0


class QuantumKernelEstimator:
    """
    Estimator for quantum kernel using SWAP test.

    The SWAP test is a quantum circuit that estimates the overlap
    (fidelity) between two quantum states without reconstructing them.

    Examples:
        >>> estimator = QuantumKernelEstimator(n_qubits=2)
        >>> from psiqit.quantum.state import random_state
        >>> state1 = random_state(4)
        >>> state2 = random_state(4)
        >>> fidelity = estimator.swap_test(state1, state2)
        >>> print(f"Fidelity: {fidelity:.4f}")
    """
    
    def __init__(self, n_qubits: int):
        """
        Initialize the quantum kernel estimator.

        Args:
            n_qubits: Number of qubits in the states to compare.
        """
        self.n_qubits = n_qubits
    
    def swap_test(self, state1: Ket, state2: Ket, shots: int = 1024) -> float:
        """
        Perform SWAP test to estimate fidelity between two states.

        Note: This is a simplified implementation that computes fidelity
        directly using inner product. A full SWAP test would require a
        controlled-SWAP circuit.

        Args:
            state1: First quantum state.
            state2: Second quantum state.
            shots: Number of measurements (not used in current implementation).

        Returns:
            Estimated fidelity between 0 and 1.

        Examples:
            >>> from psiqit.quantum.state import zero
            >>> estimator = QuantumKernelEstimator(n_qubits=1)
            >>> fidelity = estimator.swap_test(zero(), zero())
            >>> print(f"Fidelity: {fidelity:.4f}")
            1.0000
        """
        # For now, compute fidelity directly using inner product
        # This is a simplification since full SWAP test requires controlled-SWAP
        fidelity = abs(state1.inner(state2)) ** 2
        return fidelity


__all__ = [
    'KernelResult',
    'QuantumKernel',
    'QuantumKernelEstimator',
]